# Scala CircleCI 2.1 configuration file for Matchers
#
# Check https://circleci.com/docs/2.0/sample-config/ for more details
#
version: 2.1
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: cimg/openjdk:17.0

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.sbt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      # Compile
      - run:
          name: Compile
          command: cat /dev/null | sbt compile

      # Save dependency cache
      - save_cache:
          paths:
            - ~/.sbt
            - ~/.ivy2/cache
            - ~/.cache/coursier
          key: v1-dependencies-{{ checksum "build.sbt" }}

      # Run tests
      - run:
          name: Test
          command: cat /dev/null | sbt test

      # Generate scaladoc (catches doc warnings in CI)
      - run:
          name: Doc
          command: cat /dev/null | sbt doc

workflows:
  build-and-test:
    jobs:
      - build